### ISSUE TITLE
Feature: User can view a list of restaurants based on location and rating

### ISSUE THREAD

**Issue by williamzhang73** [williamzhang73/Yelp-Simplified#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### create a responsive layout showing a list of restaurants after users select a location and top rated. 

## 🖼️ Wireframes

![user can create an entry mobile](https://github.com/williamzhang73/front-end-project/assets/151261985/c4156e18-24e4-4f7c-9479-7da56d185ca8)
![user can create an entry desktop](https://github.com/williamzhang73/front-end-project/assets/151261985/7ac6588e-4045-4b2a-a142-6cf4ff52a223")

## ✅ Task List

- [ ] Create a landing page for index.html
- [ ] On the landing page, users can enter the city name, and a list of top-rated restaurants within that city will show up after hitting the search button.
- [ ] Add an event handler to the search button
- [ ] fetch data from public APIs, extract necessary data from retrieved data, and assign them to each variable.
- [ ] create a function that can create a li element
- [ ] Loop through every object in the array,  and use DOM manipulation to append every object into the unordered list
- [ ] append each li element to the parent unordered list
- [ ] div[data-landing-page="landingPage"] will hidden, and div[data-top-rated="entitiesView"] will display
- [ ] Remove any examples entries from the index.html
- [ ] Create a hyperlink for the logo, so it can always return to the main landing page.
- [ ] Clean up all unnecessary stylings
- [ ] Clean up all logs in the console
- [ ] fix all bugs
