### ISSUE TITLE
Feature: User can delete reviews

### ISSUE THREAD

**Issue by williamzhang73** [williamzhang73/Yelp-Simplified#13]
## ⚙️ Feature

Users can check the business profile.

## 📐 Functionality

After clicking the selected business on the landing page, the business profile with detailed info will be displayed.

## 🖼️ Wireframes
![user can create an entry mobile](https://github.com/williamzhang73/front-end-project/assets/151261985/c4156e18-24e4-4f7c-9479-7da56d185ca8)
![user can create an entry desktop](https://github.com/williamzhang73/front-end-project/assets/151261985/7ac6588e-4045-4b2a-a142-6cf4ff52a223")

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

  - [ ] After hitting the delete button on the My Reviews page, a dialog will pop out to confirm the action.
  - [ ] If the cancel button is clicked in the dialog, remain on the My Review page, otherwise, delete the entry from the data object and remove the entry element from the page.
  - [ ] Fix all bugs 
  - [ ] Remove unnecessary styling 
  - [ ] remove all commented-out codings
