### ISSUE TITLE
Polish

### ISSUE THREAD

**Issue by williamzhang73** [williamzhang73/Yelp-Simplified#15]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [ ] Replace the logo image with an appropriate one
- [ ] Add "no entry exists" message on the My Reviews page if no entries
- [ ] Make text in the selector consistent with the output view
