### ISSUE TITLE
Feature: User can view a list a restaurants based on location and top viewed

### ISSUE THREAD

**Issue by williamzhang73** [williamzhang73/Yelp-Simplified#2]
## ⚙️ Feature

Users can view a list of restaurants based on location and top viewed.

## 📐 Functionality

 Users can select a location and select the top viewed selector, and a list of restaurants meeting the criteria will be displayed.

## 🖼️ Wireframes

![user can create an entry mobile](https://github.com/williamzhang73/front-end-project/assets/151261985/c4156e18-24e4-4f7c-9479-7da56d185ca8)
![user can create an entry desktop](https://github.com/williamzhang73/front-end-project/assets/151261985/7ac6588e-4045-4b2a-a142-6cf4ff52a223")

## ✅ Task List

 - [ ]Add an event handler to id="ratedOrViewed" selector, once the top viewed option is clicked, a list of restaurants with the highest review number should be displayed.
 - [ ] div[data-landing-page="landingPage"] will be hidden, div[data-top-rated="entitiesView"] will be showed
 - [ ] change the subtitle to 'top viewed in the city'.
 - [ ] remove all comments
 - [ ] Remove all unnecessary styling
 - [ ] fix all bugs
