### ISSUE TITLE
Feature: User can add reviews to a specific business

### ISSUE THREAD

**Issue by williamzhang73** [williamzhang73/Yelp-Simplified#3]
## ⚙️ Feature

Users can add reviews to a specific business

## 📐 Functionality

Users can add reviews to a business with titles, ratings, and messages.

## 🖼️ Wireframes

![user can create an entry mobile](https://github.com/williamzhang73/front-end-project/assets/151261985/c4156e18-24e4-4f7c-9479-7da56d185ca8)
![user can create an entry desktop](https://github.com/williamzhang73/front-end-project/assets/151261985/7ac6588e-4045-4b2a-a142-6cf4ff52a223")

## ✅ Task List

  - [ ] After clicking each business entity image, users can view a detailed business profile.
  - [ ] Add an event handler to each business image
  - [ ] hidden other non-relevant sections, only a business profile section will be displayed
  - [ ] make it dynamic on both mobile and desktop
  - [ ] Add a review button on the page, and add an event handler to it
  - [ ] After hitting the add review button, an adding review form will display.
  - [ ] remove unnecessary styling 
  - [ ] fix all bugs
