### ISSUE TITLE
Feature: Users can update reviews

### ISSUE THREAD

**Issue by williamzhang73** [williamzhang73/Yelp-Simplified#4]
## ⚙️ Feature

Users can check the business profile.

## 📐 Functionality

After clicking the selected business on the landing page, the business profile with detailed info will be displayed.

## 🖼️ Wireframes
![user can create an entry mobile](https://github.com/williamzhang73/front-end-project/assets/151261985/c4156e18-24e4-4f7c-9479-7da56d185ca8)
![user can create an entry desktop](https://github.com/williamzhang73/front-end-project/assets/151261985/7ac6588e-4045-4b2a-a142-6cf4ff52a223")

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

  - [ ] After the update button is clicked, the review update page will be displayed
  - [ ] change the page title to "update review"
  - [ ] Pre-fill out the form with data needed to be edited
  - [ ] change the button content to "update"
  - [ ] After hitting the update button, the data object will be updated, and my reviews page will also be updated automatically
  - [ ] switch the view to my reviews page
  - [ ] remove all commented out code
  - [ ] fix all bugs
  - [ ] remove all un-necessary styling
